import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = path.join(projectRoot, "assets/css/site.css");
const sharedFiles = [
  "assets/css/core/tokens.css",
  "assets/css/core/base.css",
  "assets/css/core/layout.css",
  "assets/css/components/index.css",
  "assets/css/core/utilities.css",
  "assets/css/pages/base.css",
];
const pageFiles = {
  home: "assets/css/pages/home.css",
  plans: "assets/css/pages/plans.css",
  privacy: "assets/css/pages/privacy.css",
  referral: "assets/css/pages/referral-program.css",
};
const sourceFiles = [...sharedFiles, ...Object.values(pageFiles)];
const bundles = {
  "site-base.min.css": sharedFiles,
  "site-home.min.css": [...sharedFiles, pageFiles.home],
  "site-plans.min.css": [...sharedFiles, pageFiles.plans],
  "site-privacy.min.css": [...sharedFiles, pageFiles.privacy],
  "site-referral.min.css": [...sharedFiles, pageFiles.referral],
};

function rewriteRelativeUrls(css, sourcePath) {
  const sourceDirectory = path.dirname(sourcePath);
  const outputDirectory = path.dirname(outputPath);

  return css.replace(/url\((['"]?)([^)'"\s]+)\1\)/g, (match, quote, value) => {
    if (/^(?:data:|https?:|\/|#)/i.test(value)) return match;
    const absoluteAssetPath = path.resolve(sourceDirectory, value);
    const relativeAssetPath = path.relative(outputDirectory, absoluteAssetPath).split(path.sep).join("/");
    const normalizedPath = relativeAssetPath.startsWith(".") ? relativeAssetPath : `./${relativeAssetPath}`;
    return `url(${quote}${normalizedPath}${quote})`;
  });
}

function minifyCss(css) {
  let result = "";
  let quote = "";
  let pendingWhitespace = false;

  for (let index = 0; index < css.length; index += 1) {
    const character = css[index];
    const next = css[index + 1];

    if (quote) {
      result += character;
      if (character === "\\") {
        result += next || "";
        index += 1;
      } else if (character === quote) {
        quote = "";
      }
      continue;
    }

    if (character === "/" && next === "*") {
      index += 2;
      while (index < css.length && !(css[index] === "*" && css[index + 1] === "/")) index += 1;
      index += 1;
      pendingWhitespace = true;
      continue;
    }

    if (character === '"' || character === "'") {
      if (pendingWhitespace && result && !"{}:;,>".includes(result.at(-1))) result += " ";
      pendingWhitespace = false;
      quote = character;
      result += character;
      continue;
    }

    if (/\s/.test(character)) {
      pendingWhitespace = true;
      continue;
    }

    const punctuation = "{}:;,>";
    if (pendingWhitespace) {
      const previous = result.at(-1) || "";
      if (result && !punctuation.includes(previous) && !punctuation.includes(character)) result += " ";
      pendingWhitespace = false;
    }

    if (punctuation.includes(character) && result.endsWith(" ")) result = result.slice(0, -1);
    result += character;
  }

  return result.replace(/;}/g, "}").trim();
}

const sourceCache = new Map(
  await Promise.all(
    sourceFiles.map(async (relativePath) => {
      const sourcePath = path.join(projectRoot, relativePath);
      const css = await readFile(sourcePath, "utf8");
      return [relativePath, rewriteRelativeUrls(css, sourcePath).trim()];
    }),
  ),
);

const sections = sourceFiles.map((relativePath) => {
  return `/* Source: ${relativePath} */\n${sourceCache.get(relativePath)}\n`;
});

const banner = "/* Generated by scripts/build-css.mjs. Edit the source partials, then rebuild. */";
await writeFile(outputPath, `${banner}\n\n${sections.join("\n")}`);

await Promise.all(
  Object.entries(bundles).map(async ([filename, files]) => {
    const css = files.map((relativePath) => sourceCache.get(relativePath)).join("\n");
    await writeFile(path.join(projectRoot, "assets/css", filename), minifyCss(css));
  }),
);

console.log(
  `Built ${path.relative(projectRoot, outputPath)} and ${Object.keys(bundles).length} route bundles from ${sourceFiles.length} source files.`,
);
