import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = path.join(projectRoot, "assets/css/site.css");
const sourceFiles = [
  "assets/css/core/tokens.css",
  "assets/css/core/base.css",
  "assets/css/core/layout.css",
  "assets/css/components/index.css",
  "assets/css/core/utilities.css",
  "assets/css/pages/base.css",
  "assets/css/pages/home.css",
  "assets/css/pages/plans.css",
  "assets/css/pages/privacy.css",
  "assets/css/pages/referral-program.css",
];

function rewriteRelativeUrls(css, sourcePath) {
  const sourceDirectory = path.dirname(sourcePath);
  const outputDirectory = path.dirname(outputPath);

  return css.replace(/url\((['"]?)([^)'"\s]+)\1\)/g, (match, quote, value) => {
    if (/^(?:data:|https?:|\/|#)/i.test(value)) return match;
    const absoluteAssetPath = path.resolve(sourceDirectory, value);
    const relativeAssetPath = path.relative(outputDirectory, absoluteAssetPath).split(path.sep).join("/");
    const normalizedPath = relativeAssetPath.startsWith(".") ? relativeAssetPath : `./${relativeAssetPath}`;
    return `url(${quote}${normalizedPath}${quote})`;
  });
}

const sections = await Promise.all(
  sourceFiles.map(async (relativePath) => {
    const sourcePath = path.join(projectRoot, relativePath);
    const css = await readFile(sourcePath, "utf8");
    return `/* Source: ${relativePath} */\n${rewriteRelativeUrls(css, sourcePath).trim()}\n`;
  }),
);

const banner = "/* Generated by scripts/build-css.mjs. Edit the source partials, then rebuild. */";
await writeFile(outputPath, `${banner}\n\n${sections.join("\n")}`);
console.log(`Built ${path.relative(projectRoot, outputPath)} from ${sourceFiles.length} source files.`);
